import { gql } from '@apollo/client'

const GET_USER = gql`
    query user{
        user{
            id,
            name,
            surname,
            stripeId,
            firebaseId,
            email,
            phone,
            gender,
            createdAt,
            carts{
                carts
                {
                    id
                    userId
                    shopInfo {
                        id
                        name
                        city
                        status
                    }
                    total
                    productVariations{
                        productId
                        id
                        variationId
                        photo
                        name
                        quantity
                        color
                        size
                        brand
                        price{
                            v1
                            v2
                            discountPercentage
                        }
                    }
                }
            } 
            orders{
                id
                cartId
                createdAt
                totalDetails{
                    amountDiscount
                    amountShipping
                    subTotal
                    total
                }
                status
                shop{
                    id
                    name
                }
                shipping{
                    url
                    courier
                    code
                }
                productVariations{
                    productId
                    variationId
                    photo
                    name
                    price{
                        v1
                        v2
                        discountPercentage
                    }
                    brand
                    quantity
                    color
                    size
                }
                recipient{
                    id
                    name
                    address{
                        city
                        country
                        line1
                        line2
                        postalCode
                        state
                    }
                }
            }
        }
    }
`

export default GET_USER;