import { gql } from '@apollo/client'
import { graphql } from '../generated/gql'


const GET_USER = graphql(`
    query user{
        user{
            id,
            name,
            surname,
            stripeId,
            firebaseId,
            email,
            phone,
            gender,
            createdAt,
            carts{
                carts
                {
                    id
                    userId
                    shopInfo {
                        id
                        name
                        city
                        status
                        minimumAmountForFreeShipping
                        profilePhoto
                    }
                    total
                    productVariations{
                        productId
                        id
                        photo
                        name
                        quantity
                        maxQuantity
                        color
                        size
                        brand
                        price{
                            v1
                            v2
                            discountPercentage
                        }
                    }
                }
                warnings {
                    variationId
                }
            } 
            orders(
                limit:1000,
                offset:0
            )
            {
                id
                code
                cartId
                createdAt
                totalDetails{
                    amountDiscount
                    amountShipping
                    subTotal
                    total
                }
                status
                shop{
                    businessId
                    stripeId
                    id
                    name
                    photo
                    address{
                        postcode
                        city
                        street
                    }
                }
                shipping{
                    url
                    courier
                    code
                }
                productVariations{
                    productId
                    id
                    photo
                    name
                    price{
                        v1
                        v2
                        discountPercentage
                    }
                    brand
                    quantity
                    color
                    size
                }
                user{
                    stripeId
                    id
                    email
                    name
                    surname
                }
                recipient{
                    name
                    phone
                    address{
                        city
                        country
                        line1
                        line2
                        postalCode
                        state
                    }
                }
                history {
                    date
                    status
                  }
            }
        }
    }
`)

export default GET_USER;