export const MATERIALS = [
    //   "alpaca",
    //   "angora",
    //   "cammello",
    "cashmere",
    "lana",
    "lambswool",
    "mohair",
    "pelle",
    "seta",
    "cotone",
    "canapa",
    "juta",
    "lino",
    "flanella",
    //   "ramiè",
    //   "viscosa",
    //   "rayon",
    //   "acrilico",
    //   "elastan",
    //   "poliestere",
    //   "poliammide",
    //   "alcantara",
    //   "lurex",
    "gomma",
    //   "tencel",
    //   "modal",
    //   "polipropilene",
    //   "poliuretano",
    //   "lycra",
    "nylon",
    "gore-Tex",
    "microfibra",
    "pile",
    "stoffa",
    "chino",
    "jeans",
]