
//TODO eliminare MATERIALS
export const MATERIALS = [
    "acrilico",
    "alcantara",
    "canapa",
    "cashmere",
    "chiffon",
    "chino",
    "cotone",
    "eco-pelle",
    "flanella",
    "gore-Tex",
    "gomma",
    "jeans",
    "lana",
    "lino",
    "lycra",
    "microfibra",
    "misto cashmere",
    "misto cotone",
    "misto lana",
    "misto lino",
    "misto poliestere",
    "misto seta",
    "neoprene",
    "nylon",
    "pelle",
    "pile",
    "poliestere",
    "popeline",
    "raso",
    "seta",
    "stoffa",
    "taffeta",
    "tencel",
    "tulle",
    "velvet",
    "velluto",
    "velluto a coste",
    "viscosa",
];

export const MATERIALS_TYPES = [
    {
        name: 'clothes_materials',
        type: [
            "acrilico",
            "alcantara",
            "canapa",
            "cashmere",
            "chiffon",
            "chino",
            "cotone",
            "eco-pelle",
            "flanella",
            "gore-Tex",
            "gomma",
            "jeans",
            "lana",
            "lino",
            "microfibra",
            "misto cashmere",
            "misto cotone",
            "misto lana",
            "misto lino",
            "misto poliestere",
            "misto seta",
            "nylon",
            "pelle",
            "pile",
            "poliestere",
            "raso",
            "seta",
            "stoffa",
            "taffeta",
            "tencel",
            "velvet",
            "velluto",
            "velluto a coste",
            "viscosa",
        ]
    },
    {
        name: 'bag_materials',
        type: [
            "pelle",
            "materiale riciclato",
            "finta pelle",
            "cotone",
            "jeans",
            "lino",
            "raso",
            "pelliccia finta",
            "velluto/nicki",
            "viscosa",
            "lyocell",
            "altro materiale"
        ]
    },
    {
        name: 'jewellery_materials',
        type: [
            "argento",
            "acciaio inossidabile",
            "pelle",
            "oro",
            "altro materiale"
        ]
    }

]